### ISSUE TITLE
Admin Properties Fails

### ISSUE THREAD

**Issue by r3ap3r2004** [jsqu99/spree_flexi_variants#1]
Adding new product properties fails with the error.

```
ActionView::Template::Error (undefined method `is_hidden' for #<Property:0x000001045aa438>):
    12: 
    13: <%= f.field_container :is_hidden do %>
    14:   <%= f.label :is_hidden, t("is_hidden") %><br />
    15:   <%= f.check_box :is_hidden %>
    16:   <%= f.error_message_on :is_hidden %>
    17: <% end %>
```

Why is :is_hidden being used here when it doesn't seem to exist anywhere?  Other than that, there is no reason to override this particular template.

**Comment by jsqu99** [comment]
Thanks for reporting.  That file must have been laying around since a very early version of the extension.

I just removed it.  Feel free to ask me any other questions / report any bugs.

I'm currently working on writing lots of tests.
