### ISSUE TITLE
Image upload doesnt work

### ISSUE THREAD

**Issue by Fodoj** [jsqu99/spree_flexi_variants#13]
Added customization type with image calculator, added it to product. Then choose file in file field, then added to cart. Result - no image saved. Rails 3.1, sqlite3, edge spree.

**Comment by jsqu99** [comment]
Thanks for reporting.

I haven't done any testing yet on the 3.1-enabled spree.

My suspicsion is a change in the hooks (see lib/spree_flexi_variants_hooks.rb for some important files e.g. content_for_head that need to get included.  I'll look at 3.1 support asap).

**Comment by chrt00** [comment]
I had a similar problem where CarrierWave would not load, thus failing the image upload.
I think rails g spree:site and rails railtie:spree_flexi_variants:install does not help you configure it.

I am running both edge versions of spree (0.70) and spree_flexi_variants, Rails 3.1

Adding require statements in the initializer fixed it for me.
https://gist.github.com/1205419

**Comment by jsqu99** [comment]
Thanks Chris.  I'm going to be revisiting 3.1 shortly and will dig deeper.

**Comment by chrt00** [comment]
No problem!

**Comment by nhunzaker** [comment]
@chrt00 I'm getting a similar problem with CarrierWave, you added that gist to initializers/spree_config.rb?

EDIT: Yeah that worked great, but I also had to add carrierwave to my gemfile. Odd, yes?

**Comment by jsqu99** [comment]
@nhunzaker what branch are you using?  I'm happy to help.  3.1 support should be pretty solid, although you might have to tweak the instructions (and ill update the readme if so).

thanks

**Comment by nhunzaker** [comment]
0.70, but everything is working wonderfully now

**Comment by jsqu99** [comment]
excellent, glad to hear.  let me know if there are any readme changes i should make
