### ISSUE TITLE
Product price incl. Tax/VAT

### ISSUE THREAD

**Issue by ArjanL** [jsqu99/spree_flexi_variants#17]
Is there a solution to show prices including Tax/VAT on the product detail page?

**Comment by jsqu99** [comment]
Hello.

Are you referring to flexi-varaint-specific tax?  If so, the answer is no.

FYI, I'm working on a complete rewrite, and I'm looking at taking into account skus, inventory, on a per-variant level.  

So, if tax is one of those items that is important to you, feel free to write up a paragraph or two on how you'd like to see it work, and I'll consider it for version 2.  thanks!

**Comment by ArjanL** [comment]
No its just base price, at this moment in _pricing.html.erb 

``` ruby
    var base_price=<%= @product.price %>;
```

 this shows the price without VAT, when i change this line to

``` ruby
var base_price=<%= product_price(@product) %>;
```

it shows the price including VAT but when i select some Ad Hoc Option Values the price update doesn't work anymore.

**Comment by jsqu99** [comment]
Oh I see.

the javascript simply applies the bare price when you change the ad hoc options.

You could always write a small amount of code to override this behavior.

hope that helps

**Comment by ArjanL** [comment]
Fixed, i added this:

``` ruby
    // 'updatePrice()' takes the base price + current 'configuration' adjustments + 'customization' adjustments
    <%=
        price_btw = @product.price
        price_btw = price_btw / 100
        price_btw = price_btw * 106
    %>
    var base_price=<%= price_btw %>;

    // keep track of ad_hoc adjustments
```

VAT for the products is 6%, there should be a more elegant method for this by using the VAT Calculator but this works for me atm!
