### ISSUE TITLE
 "uninitialized constant Admin::OptionTypesController" when running install

### ISSUE THREAD

**Issue by KristianHildebrandt** [jsqu99/spree_flexi_variants#18]
Not much more to say. I just tried to install spree along with your extension, but getting this error when running "bundle exec rails g spree_flexi_variants:install" :

uninitialized constant Admin::OptionTypesController (NameError)

I run ruby version 1.9.2 with rails 3.1.2.

Any Ideas?

**Comment by jsqu99** [comment]
Spree master? Not yet compatible. That controller has recently been renamed Spree::Option....

Try spree 0.70.2

**Comment by KristianHildebrandt** [comment]
Well, I used the lates Spree because on older versions I get the following error, when running "rake db:bootstrap" :

"undefined method `register_calculator' for ProductCustomizationType(Table doesn't exist):Class"

**Comment by jsqu99** [comment]
Sorry you are having problems.  Hopefully I can get you through them.

So recently spree changed the way they do the calculator registrations.  I don't recall offhand(but can investigate shortly) exactly at what point that change went into place.

There used to be a config section where they did something like [FlatRate, FlexiRate, etc].map(&:register)

and now they use some kind of railtie mechanism:

initialier do
  my calcs << FlatRate, etc
end

Sorry, going from memory.  I'll try to get you more detail later today.

I'll help you get through this! :-)

**Comment by jsqu99** [comment]
Another user has reported this and I just spent some time looking into it.  It's definitely a spree 0-70-stable integration issue.

I'm looking into this

**Comment by KristianHildebrandt** [comment]
Out of curiosity, for which version does flexi_variants work?

**Comment by jsqu99** [comment]
That's a great question :-)

Up until a few days ago, I thought it was 0.70.x.

I'm positive that the 0.60.x branch of spree works w/ flexi variants (if master fails, try the pre-deface-stable branch).

Hopefully we'll get this double-migration issue straightened out shortly

**Comment by jsqu99** [comment]
and btw, I'm not sure i communicated this with you (been working w/ a few different people).

https://github.com/jsqu99/spree_flexi_variants/blob/master/lib/spree_flexi_variants.rb#L25

causes us to ignore that error when the table does not yet exist.

That should get you to this error: http://groups.google.com/group/spree-user/browse_thread/thread/80810dc0d907d6ac#

Which can probably be worked around by deleting the flexi variant migratinons in db/migrations

**Comment by jsqu99** [comment]
I'm fairly certain I've got a working extension again.  This was diffcult to figure out.

What was happening was there was a rake task that was getting executed implicitly that was double-copying migrations.

Please take a look and let me know if you have any more problems.
