### ISSUE TITLE
error running rails g spree_flexi_variants:install

### ISSUE THREAD

**Issue by gerardocastro** [jsqu99/spree_flexi_variants#21]
Hi, when i run rails g spree_flexi_variants:install i get this

/home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/bundler/gems/spree_flexi_variants-0c467e354c3c/app/models/calculator/engraving.rb:1:in `<top (required)>': wrong argument type Module (expected Class) (TypeError)
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:456:in`load'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:456:in `block in load_file'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:640:in`new_constants_in'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:455:in `load_file'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:342:in`require_or_load'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:489:in `load_missing_constant'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:181:in`block in const_missing'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:179:in `each'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:179:in`const_missing'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/bundler/gems/spree_flexi_variants-0c467e354c3c/lib/spree_flexi_variants.rb:29:in `block in <class:Engine>'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/railties-3.1.1/lib/rails/initializable.rb:30:in`instance_exec'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/railties-3.1.1/lib/rails/initializable.rb:30:in `run'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/railties-3.1.1/lib/rails/initializable.rb:55:in`block in run_initializers'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/railties-3.1.1/lib/rails/initializable.rb:54:in `each'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/railties-3.1.1/lib/rails/initializable.rb:54:in`run_initializers'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/railties-3.1.1/lib/rails/application.rb:96:in `initialize!'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/railties-3.1.1/lib/rails/railtie/configurable.rb:30:in`method_missing'
    from /home/gerardo/projects/os/config/environment.rb:5:in `<top (required)>'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:240:in`require'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:240:in `block in require'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:223:in`block in load_dependency'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:223:in`load_dependency'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:240:in `require'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/railties-3.1.1/lib/rails/application.rb:83:in`require_environment!'
    from /home/gerardo/.rvm/gems/ruby-1.9.2-p136@os/gems/railties-3.1.1/lib/rails/commands.rb:22:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

this is my gem file

gem 'rails', '3.1.1'
gem 'spree', :git => 'git://github.com/spree/spree.git'
gem 'spree_blue_theme', :git => 'git://github.com/spree/spree_blue_theme.git'
gem 'spree_static_content', :git => 'git://github.com/spree/spree_static_content.git'
gem 'spree_flexi_variants', :git=>'git@github.com:jsqu99/spree_flexi_variants.git'

group :development, :test do
  gem 'mysql2', '> 0.3'
end

gem 'deface', :git => 'git://github.com/railsdog/deface.git'

I hope anyone can help me with this thanks.

**Comment by jsqu99** [comment]
You are referencing spree 1.0.0.rc\* in your Gemfile (implicitly), and unfortunately this extension has not yet been upgraded to support 1.0.
