### ISSUE TITLE
bundle exec rails g spree:site

### ISSUE THREAD

**Issue by serialbandicoot** [jsqu99/spree_flexi_variants#22]
os: mac lion
ruby 1.9.3
rails 3.1.3

After running the following I got a build error:

Mac-Airs-MacBook-Air:mystore macair$ bundle exec rails g spree:site
/Users/macair/.rvm/gems/ruby-1.9.3-p0/bundler/gems/spree_flexi_variants-639ffc779d35/app/models/calculator/engraving.rb:1:in `<top (required)>': wrong argument type Module (expected Class) (TypeError)

**Comment by jsqu99** [comment]
Hello. Spree version please? Gemfile?

**Comment by serialbandicoot** [comment]
gem 'rails', '3.1.3'
gem 'mysql2'

group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :test do
  # Pretty printed test output
  gem 'turn', '~> 0.8.3', :require => false
end
gem 'spree', '1.0.0.rc4'
#gem 'spree', :git => 'git://github.com/spree/spree.git', :branch =>
'0-70-stable'
gem 'spree_usa_epay', :git => 'git://github.com/spree/spree_usa_epay.git',
:ref => '0cb57b4afbf1eef6a0ad67a4a1ea506c6418fde1'
gem 'spree_skrill', :git => 'git://github.com/spree/spree_skrill.git', :ref
=> '37e6159aa71ec053499e2c7aa9cf799a3b3bdb39'

gem 'rmagick'
gem 'carrierwave'
gem 'spree_flexi_variants', :git=>'git://
github.com/jsqu99/spree_flexi_variants.git'

Also tried spree 1.0.0

It looks like it's due to Namespacing changes and I tried changing the
Spree Calculator to Spree::Calculator, which seemed to work however this
then led to:

spree_flexi_variants-639ffc779d35/app/controllers/admin/line_items_controller_decorator.rb:1:in
`<top (required)>': uninitialized constant Admin::LineItemsController

Sam

On 16 February 2012 00:52, jsqu99 <
reply@reply.github.com

> wrote:
> 
> Hello. Spree version please? Gemfile?
> 
> Sent from my iPhone
>

**Comment by jsqu99** [comment]
Thanks for the info. 

Unfortunately I'm not yet spree 1.0 ready but will be very soon.

**Comment by serialbandicoot** [comment]
No worries Let me know when your near there and I can run some testing on
it. It's got the perfect requirement for a site I'm working on.

Cheer,
Sam

samtreweek at gmail dot com

On 16 February 2012 08:42, jsqu99 <
reply@reply.github.com

> wrote:
> 
> Thanks for the info.
> 
> Unfortunately I'm not yet spree 1.0 ready but will be very soon.
> 
> Sent from my iPhone
>

**Comment by jsqu99** [comment]
Thanks. Feel free to help out and submit a pull request :-). Shouldn't be hard to upgrade. Asset pipeline and namespace changes for the most part
