### ISSUE TITLE
NoMethodError in OrdersController#update

### ISSUE THREAD

**Issue by handcrab** [jsqu99/spree_flexi_variants#24]
Hi 
I'm using spree 0.6 with flexi variants.
But removing via frontend any product with Ad Hoc Option Type from cart raises an error:
**NoMethodError in OrdersController#update
undefined method `eq' for nil:NilClass**

Request
Parameters:
{"utf8"=>"✓",
 "_method"=>"put",
 "authenticity_token"=>"I0Zk8MRl8/nBUTR4iAcLAJrCY5QFZPVjt+H4feR7IXQ=",
 "order"=>{"line_items_attributes"=>{"0"=>{"quantity"=>"0",
 "id"=>"1"}}}}

Gemfile:

```
gem 'rails', '3.0.10'
gem 'sqlite3'
gem 'spree', '~> 0.60.4'
gem 'spree_flexi_variants', :git=>'git@github.com:jsqu99/spree_flexi_variants.git', :branch => 'spree-0-60-stable'
```

**Comment by jsqu99** [comment]
I'll take a look at this shortly

**Comment by jsqu99** [comment]
I was able to reproduce.  investigating

**Comment by jsqu99** [comment]
Thanks for reporting.  It turns out I had fixed this in the other branches.  I cherry picked a migration that adds a needed primary key to ad_hoc_line_items table.

Please grab the latest and give it a try.

**Comment by handcrab** [comment]
Thank you for fast fix! Now it really works nice.

**Comment by jsqu99** [comment]
that's great to hear!
