### ISSUE TITLE
production: error 500 on product page

### ISSUE THREAD

**Issue by wandtasie** [jsqu99/spree_flexi_variants#31]
Hi

Playing around with spree_flexi_variants in production mode I get an error 500 on products page.
I used a fresh spree sample shop (1.0.3) with spree_flexi_variants (master), precompiled assets, correct file permissions...

``` bash
ActionView::Template::Error (store/flexi-variants.css isn't precompiled):
    66: <% else %>
    67:   <%= content_for :head do %>
    68:
    69:   <%= stylesheet_link_tag 'store/flexi-variants' %>t
    70:
    71:   <%= javascript_tag do %>
    72:     var cartFormValidator;
```

 The same problem appears with other files like the jquery.validation... and exclusions.js linked in spree_flexi_variants view files.

I figured out that the problems root is in the config. Rails needs know the files via app.config.assets.precompile (look at: https://github.com/wandtasie/spree_flexi_variants/commit/331f4fc82ce803cf8848dc18121b5bc4671201b2 )

I have done some changes including this at my fork https://github.com/wandtasie/spree_flexi_variants.
I`ll close my old pull request https://github.com/jsqu99/spree_flexi_variants/pull/30 and open a new one including the additional changes.

Maybe someone can verify this issue?

**Comment by daemonsy** [comment]
Hi, I'm using the MASTER branch on Spree 1.0.3 and I'm having this same issue as well.

**Comment by wandtasie** [comment]
@deamonsy my fork https://github.com/wandtasie/spree_flexi_variants solves this. Pull request is still open. you can install my fork and give a feedback?

**Comment by daemonsy** [comment]
I actually wanted to install your branch. It seems to work okay. Sadly, I already installed and did rails g spree_flexi_variants:install for the master branch. So now I'm having a lot of tiny issues (e.g. flexi-variants and spree-flexi-variants.css) and I'm trying to get it sorted out =)

**Comment by wandtasie** [comment]
@daemonsy delete the lines added by spree_flexi_variants in your rails app/assets/stylesheets/store/all.css and javascripts/store/all.js. then reinstall spree_flexi_variants...

**Comment by jsqu99** [comment]
I'm so sorry.  I usually respond immediately to issues filed, but somehow I missed seeing this one.

Unfortunatly I'm on vacation in the mountains ATM and i'm not sure when i'll be able to take a look.  ASAP though.

thanks everyone

**Comment by jsqu99** [comment]
I just pulled.  Sorry for the wait!

**Comment by jsqu99** [comment]
will do more verification when back from vacation.  thanks for reporting

**Comment by wandtasie** [comment]
@jsqu99 thanks I got some additional ideas but the pull request was growing...
Enjoy your hollidays
