### ISSUE TITLE
Percentage based change for Ad-hoc Option Types

### ISSUE THREAD

**Issue by daemonsy** [jsqu99/spree_flexi_variants#32]
Firstly, thanks a lot for this extension! For my use cases so far, I think such a system of adding a price increase to an option value is much more practical than Spree's native variant. 

Is there any interest (or is there a way) to set the price changes to an ad-hoc option as a percentage of the master price?

**Comment by jsqu99** [comment]
Hey thanks a lot for the compliment.

So if you want a percentage-based pricing you'd have to use the customizations(custom calculators), not the ad hoc options.

It certainly would make more sense to us ad hoc options, but those don't (yet?) support percentages (want to send a pull request? :) ) .

**Comment by daemonsy** [comment]
I want to help... but I'm a little noob. Let me give it a try =)

**Comment by jsqu99** [comment]
Sounds great.  don't worry, i was a noob not too long ago :-)

**Comment by jsqu99** [comment]
there is a branch here i'm using for one client that works great.  check it out
