### ISSUE TITLE
Template is missing

### ISSUE THREAD

**Issue by dp6ai** [jsqu99/spree_flexi_variants#33]
Hi,

Just installed and getting the following:

Template is missing
Missing template spree/admin/option_types/available_ad_hoc, spree/admin/resource/available_ad_hoc, spree/admin/base/available_ad_hoc, spree/base/available_ad_hoc, application/available_ad_hoc with {:handlers=>[:erb, :builder, :coffee], :formats=>[:html], :locale=>[:"en-GB", :en]}. Searched in: \* "/Library/WebServer/Documents/site/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/bundler/gems/spree_flexi_variants-8a5004c6fc9d/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/gems/spree_slider-1.0.1/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/bundler/gems/spree_essential_cms-097954bd58d6/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/gems/spree_essentials-0.4.0.rc3/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/bundler/gems/spree_related_products-dcac3c3aff2b/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/bundler/gems/spree_skrill-37e6159aa71e/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/gems/spree_promo-1.0.3/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/gems/spree_dash-1.0.3/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/gems/spree_api-1.0.3/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/gems/spree_auth-1.0.3/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/gems/devise-1.4.8/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/gems/spree_core-1.0.3/app/views" \* "/Users/user/.rvm/gems/ruby-1.9.2-p290@spree/gems/kaminari-0.13.0/app/views"

---

Gemfile looks like this:

source 'http://rubygems.org'

gem 'rails', '3.1.3'

group :production do
  gem 'pg'
end
group :development, :test do
  gem 'sqlite3'
end
# Gems used only for assets and not required
# in production environments by default.

group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
# Use unicorn as the web server

gem 'unicorn'
# Deploy with Capistrano
# gem 'capistrano'
# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', '~> 0.8.3', :require => false
end
gem 'spree'
gem 'spree_skrill', :git => 'git://github.com/spree/spree_skrill.git', :ref => '37e6159aa71ec053499e2c7aa9cf799a3b3bdb39'
gem 'spree_related_products', :git => 'git://github.com/spree/spree_related_products.git'
gem 'spree_i18n', :git => 'git://github.com/spree/spree_i18n.git'
# gem "spree_paypal_website_standard", :git => "git://github.com/tomash/spree-pp-website-standard.git"

gem 'spree_essential_cms', :git => 'git://github.com/citrus/spree_essential_cms.git'
gem 'pg'
gem 'spree_heroku', :git => 'git://github.com/joneslee85/spree-heroku.git'
gem 'delayed_job_active_record'
gem 'spree_autosuggest', :git => 'git://github.com/evrone/spree_autosuggest.git'
gem 'spree_clean'
gem 'spree_slider'
gem 'aws-s3'
gem 'spree_gateway', :git => "git://github.com/spree/spree_gateway"
gem 'newrelic_rpm'
gem 'rmagick'
gem 'carrierwave'
gem 'spree_flexi_variants', :git => 'git://github.com/jsqu99/spree_flexi_variants.git'

**Comment by jsqu99** [comment]
I'll take a look at this ASAP.  I"m on vacatino ATM but will tryu to address shortly

**Comment by dp6ai** [comment]
Thanks Jeff,

Will the extension allow me to do the following:

Does anyone know if there is a way of creating a variant of a product that
does not have an "on hand" value (it uses its master on hand value).

I want to sell tables which have the option of a glass top  but i dont want
this variant to have a separate value for on hand i want it to decrease the
overall stock of the tables.

ie

tables OH = table+Glass OH =50

a user buy a table+glass

tables OH = table+Glass OH =49

i think i need to have a master product on hand but still use the variants
which doesn't seem possible.

Hope this makes sense.

thanks

DP

On Thu, Apr 12, 2012 at 2:19 PM, Jeff Squires <
reply@reply.github.com

**Comment by jsqu99** [comment]
I'm not sure about that one.  you might want to post that question to the spree google group.  

this version of flexi varaints doesn't take inventory into account (but there are plans for the next version to do this)

**Comment by dp6ai** [comment]
That sounds perfect (I think). Surely I could add a master product then add ad hoc variants with a price through your extension. (maybe?)

**Comment by wandtasie** [comment]
@dp6ai look at: http://guides.spreecommerce.com/inventory.html#overview

**Comment by dp6ai** [comment]
I've looked over the document a few times and it doesn't seem that spree
will handle what i need?

Am i missing something?

What i need is the ability to add a variant which is not inventory
controlled so but does have a separate price (so a product option is not
possible).

Will flexi_variants achieve this? or is there another way?

thanks

DP

On Thu, Apr 12, 2012 at 9:27 PM, Matthias Wagner <
reply@reply.github.com

**Comment by jsqu99** [comment]
Flexi variants doesn't currently do anything with inventory. Try spree google group?

**Comment by wandtasie** [comment]
@dp6ai is your issue solved?

**Comment by dp6ai** [comment]
I didn't end up using flex so i don't know whether the issue was resolved
sorry.

On Wed, Apr 18, 2012 at 12:09 AM, Matthias Wagner <
reply@reply.github.com

**Comment by wandtasie** [comment]
@dp6ai you can close the issue? I think this issue wasn't related to spree_flexi_variants...
