### ISSUE TITLE
1-0-stable for spree_flexi_variants?

### ISSUE THREAD

**Issue by wandtasie** [jsqu99/spree_flexi_variants#34]
@jsqu99 you can add a 1-0-stable branch? so we can start testing with upcoming 1-1-stable version of spree?

Thanks

**Comment by wandtasie** [comment]
I just added the 1-0-stable branch to my fork. If I get it running, I'll send you a pull request

**Comment by jsqu99** [comment]
Thanks.  I'm going to be looking at some extension issues shortly.

**Comment by wandtasie** [comment]
https://github.com/jsqu99/spree_flexi_variants/pull/36
