### ISSUE TITLE
spree_promo not working when spree_flexi_variants is used

### ISSUE THREAD

**Issue by krismartin** [jsqu99/spree_flexi_variants#35]
I can't seem to get Spree Promotion working when spree_flexi_variants gem is used in my app.

The promotion I have setup is based on 'Add to Card' event and supposed to create an adjustment (flat percentage) to the Order, but no adjustment was ever made.

I'm using spree 0.70.5 and spree_flexi_variants spree-0-70-stable.

spree_promo is working fine when I remove spree_flexi_variants gem from my Gemfile.

**Comment by jsqu99** [comment]
I'll take a look at this shortly.  thanks.

**Comment by wandtasie** [comment]
@jsqu99 orders_populate doesn't fire events
https://github.com/jsqu99/spree_flexi_variants/blob/master/app/controllers/spree/orders_controller_decorator.rb

look at:
https://github.com/spree/spree/blob/3c81e2140021a99c76f157841376bc401e4ca56a/core/app/controllers/spree/orders_controller.rb
Edit: https://github.com/spree/spree/blob/0-70-stable/core/app/controllers/orders_controller.rb

I don't know how promo changes prices and how the ahov prices are affected...

**Comment by jsqu99** [comment]
i just pushed a fix for this. thanks!

**Comment by wandtasie** [comment]
:-)

**Comment by krismartin** [comment]
That was quick. Thanks! :)

**Comment by jsqu99** [comment]
thanks!  the only problem is, can you please test? :-)

sorry for not having better test coverage.  want to help w/ that?

**Comment by krismartin** [comment]
OK, I have tested this with my Promotion (add to cart event, flat percentage adjustment) and it is working perfectly. The correct adjustment was made to the Order.

I haven't tested it with any other types of promotion (e.g. coupon code, user sign up, etc).

I'll see if I can help you with writing the test for this.

**Comment by jsqu99** [comment]
Whew!
