### ISSUE TITLE
Custom calculators don't work

### ISSUE THREAD

**Issue by Deaner666** [jsqu99/spree_flexi_variants#4]
I've created a custom calculator and registered it with spree in a Rails initializer:

``` ruby
    [
        Calculator::FlatRateForOption
    ].each{ |c_model|
        begin
            c_model.register if c_model.table_exists?
        rescue Exception => e
            $stderr.puts "Error registering calculator #{c_model}"
        end
    }
```

The custom calculator model registers itself with the ProductCustomizationType model:

``` ruby
    class Calculator::FlatRateForOption < Calculator
        preference :price, :decimal

    def self.description
        "Flat Rate Calculator"
    end

    def self.register
        super
        ProductCustomizationType.register_calculator(self)
    end

    def create_options
        # This calculator knows that it needs one CustomizableOption named text
        [ CustomizableProductOption.create(:name => "text", :presentation => "Text to embroider" , :data_validation => ( {:type => :string, required => false}).to_json )]
    end

    def compute(product_customization)
        return 0 unless valid_configuration? product_customization
        # expecting only one CustomizedProductOption
        opt = product_customization.customized_product_options.detect {|cpo| cpo.customizable_product_option.name == "text" }
        rescue ''
        self.preferred_price
    end

    def valid_configuration?(product_customization)
        true
    end
end
```

However, when adding a product customization type in the admin interface, the new calculator only seems to stick around for the initial request. I restart the server, add a new product customization type using the new calculator, it correctly takes me to the edit page with the first customizable option correctly created, but the new calculator now no longer exists in the drop down box of calculators. This means when you submit the edited form it creates an error:

```
Couldn't find Calculator with ID=7 for ProductCustomizationType with ID=4
```

**Comment by Deaner666** [comment]
Forgot to mention I'm using the pre-deface-stable branch with Spree 0.60.0

**Comment by Deaner666** [comment]
Shouldn't the FlatRate calculator that already ships with Spree be included in the default set of calculators available to spree_flexi_variants? All I really want to do is use the FlatRate calculator on a product customization... ie. like the inscription on your cake demo, but with a flat price for the inscription, not a price per letter. But I couldn't find a way to get that to work, so tried to roll my own... which also didn't work!

**Comment by Deaner666** [comment]
Ah. Just found the problem. What I was trying doesn't work from a Rails initializer (although the official Spree documentation says it should do.) It does seem to work from within `lib/spree_site.rb` though. I'll let you know if I have any further issues with this method.

**Comment by jsqu99** [comment]
Thanks for reporting, and I'm glad you figured it out.

FYI, disregard all of the official spree docs regarding calculators when it comes to their use in this extension.  I just stole the idea from spree and tweaked calculators for use here.  There are some extension-specific components of the calculators (e.g.   def create_options) meaning that 'normal' spree calculators won't work.

**Comment by jsqu99** [comment]
In general, just copy the contents of an existing calculator and modify as needed for your new calculator.  No need to mess w/ rails initializers
