### ISSUE TITLE
product_customization_types_products not namespaced

### ISSUE THREAD

**Issue by binaryphile** [jsqu99/spree_flexi_variants#42]
Edge master as of today includes namespace migrations for every table except product_customization_types_products.  It looks so lonely sitting there. ;)

**Comment by jsqu99** [comment]
you know i actaully noticed that today.  not sure if that was an accidental omission or i couldn't get the association to work correctly w/ the rename (i'm guessing the latter).  care to send a pull request? :-)

**Comment by binaryphile** [comment]
Sure, but I'm not sure I understand migrations.  What would have to happen?

**Comment by wandtasie** [comment]
I think, the join-table needs an explicit name

https://github.com/spree/spree/blob/master/core/app/models/spree/taxon.rb#L6
https://github.com/spree/spree/blob/master/core/app/models/spree/product.rb#L27

or using a join model is a very flexible solution ... (has_many :through)

**Comment by jsqu99** [comment]
I'm going to close this unless someone wants to provide a pull request that doesn't involve an empty rails model...or if i'm mistaken...jsut let me know
