### ISSUE TITLE
How do I add a custom calculator without forking?

### ISSUE THREAD

**Issue by sfcgeorge** [jsqu99/spree_flexi_variants#44]
Hi, I have the same issue as https://github.com/jsqu99/spree_flexi_variants/issues/12 but after hours of trying and reading your answer I still couldn't get it to work. The only way I could make my own custom calculator work was to fork your spree_flexi_variants repo and add my calculator to it directly. This feels like a rather clunky hack.

I'm building a made-to-measure curtains store, so I have created the following files to make my own custom calculator:

app/models/spree/calculator/curtain_area.rb
app/views/spree/products/customizations/calculator/_curtain_area.html.erb
app/views/spree/products/customizations/calculator_type/_curtain_area.html.erb

I changed the line in lib/spree_flexi_variants/engine.rb to:

app.config.spree.calculators.product_customization_types = [
                                                                    Spree::Calculator::Engraving,
                                                                    Spree::Calculator::AmountTimesConstant,
                                                                    Spree::Calculator::ProductArea,
                                                                    Spree::Calculator::CustomizationImage,
                                                                    Spree::Calculator::CurtainArea
                                                                   ]

And it works. The problem is of course, every time a new version of Spree comes out and you update spree_flexi_variants to be compatible or you add features, I have to stop server, merge them into my fork, commit, push, bundle update, start server - what I'm doing is a mess, I must be doing it wrong?

So ideally I would be able to use your spree_flexi_variants gem directly without forking it, and put my own custom calculator somewhere in my app. My questions are:
1. Where should I put the 3 calculator files I've created? In a subfolder of my main Spree app maybe, or do I stick them in a new engine, or somewhere else?
2. How do I register those files so they show up in the spree_flexi_variants interface and work? I tried appending to the product_customization_types in an initialiser or something but couldn't make it work.

I'm sorry if I'm missing the obvious. I just watched a screencast on engines but they still confuse me.

Any help would be greatly appreciated.

Thanks,
Simon

**Comment by jsqu99** [comment]
Hello,

You don't have to fork.  This should be quite easy for you.  here's how:

in config/application.rb

```
initializer "whatevermyapp.register.calculators" do |app|
```

app.config.spree.calculators.product_customization_types.concat([Spree::Calculator::
CurtainArea])
    end

Put these files in your app:

app/models/spree/calculator/curtain_area.rb

> app/views/spree/products/customizations/calculator/_curtain_area.html.erb
> 
> app/views/spree/products/customizations/calculator_type/_curtain_area.html.erb
> 1. Where should I put the 3 calculator files I've created? In a subfolder
>    of my main Spree app maybe, or do I stick them in a new engine, or
>    somewhere else?

just in the app in those correct paths that your have

> 1. How do I register those files so they show up in the
>    spree_flexi_variants interface and work? I tried appending to the
>    product_customization_types in an initialiser or something but couldn't
>    make it work.
> 
> see above.
> 
> I'm sorry if I'm missing the obvious. I just watched a screencast on
> engines but they still confuse me.

the trick is registeringing them in your application.rb

HTH

**Comment by sfcgeorge** [comment]
Thank you very much for the quick reply. I followed your instructions and now it works perfectly. If I find time between client work and exams I could update the readme / wiki to include these instructions.

**Comment by jsqu99** [comment]
excellent, glad i could help

On Mon, May 21, 2012 at 2:14 PM, sfcgeorge <
reply@reply.github.com
