### ISSUE TITLE
RuntimeError in Spree::CheckoutController#edit

### ISSUE THREAD

**Issue by wandtasie** [jsqu99/spree_flexi_variants#48]
Hi jeff

The following error appears sometimes if I go to checkout (in frontend) instantly after login. 
(using spree 1-1-stable): https://gist.github.com/2965961

I think its related to the changes to order model the last months like this:
https://github.com/spree/spree/commit/654dab62e55912389897c2b95defb2936827b577

and this:
https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb#L473

At the moment I don't figured out how to fix this, but maybe we can work together...

**Comment by jsqu99** [comment]
my suspicion is you are sending in a null variant here; https://github.com/wandtasie/spree/blob/master/core/app/models/spree/order.rb#L457

i don't know how else you could have a crash here: https://github.com/jsqu99/spree_flexi_variants/blob/master/app/models/spree/order_decorator.rb#L48

**Comment by wandtasie** [comment]
Sorry I pointed the links to my fork, which isn't causing the problem. (now updated above)

the line item validates presence of variant:
https://github.com/spree/spree/blob/master/core/app/models/spree/line_item.rb#L12

**Comment by wandtasie** [comment]
I tried some time to reproduce this error with a fresh spree shop and I couldn't reproduce it. I'll close this issue for the moment and try to figure out what happens. 
Possibilities are: 
  The issue appears after a deploy
  It appears only if variants and ad hoc options used in the same product
  It's something with my local app

Thanks for your suspicions...
