### ISSUE TITLE
Ahots disappear after relogin

### ISSUE THREAD

**Issue by wandtasie** [jsqu99/spree_flexi_variants#49]
Steps to reproduce:
1. Fresh spree demo installation(1-1-stable) with spree_flexi_variants.
2. Add ahot to a product.
3. Add the same product to cart.
4. Logout.
5. Add another product to cart.
6. Use the checkout button at the cart.
7. Login.
8. Somehow the cart gets merged.
9. And the ahots are gone.

Although we need some steps to reproduce this, the scenario Isn't unrealistic. If a user returns after some time is gone or switches the computer, this is exactly what happens.

If I logout and relogin without adding another product, the ahots display as expected...

**Comment by jsqu99** [comment]
are you referring to spree_demo ?  That extension needs some tweaking for flexi integration, IIRC

**Comment by wandtasie** [comment]
Sorry, no time at the moment, later or better tomorrow would be great. I got a lot of tweaks and errors (all around spree and extensions) at the moment... the shop system is growing :-) Thanks for reply

**Comment by wandtasie** [comment]
Some additions: I get periodical the following error which is related to the login as well:

``` bash
RuntimeError in Spree::CheckoutController#edit

Called id for nil, which would mistakenly be 4 -- if you really wanted the id of nil, use object_id

Rails.root: /home/matthias/public_html/spree_wandtasie
Application Trace | Framework Trace | Full Trace

/home/matthias/.rvm/gems/ruby-1.9.3-p125/bundler/gems/spree_flexi_variants-7443a8462000/app/models/spree/order_decorator.rb:48:in `block in contains?'
activerecord (3.2.6) lib/active_record/associations/collection_proxy.rb:89:in `each'
activerecord (3.2.6) lib/active_record/associations/collection_proxy.rb:89:in `detect'
activerecord (3.2.6) lib/active_record/associations/collection_proxy.rb:89:in `method_missing'
/home/matthias/.rvm/gems/ruby-1.9.3-p125/bundler/gems/spree_flexi_variants-7443a8462000/app/models/spree/order_decorator.rb:47:in `contains?'
/home/matthias/.rvm/gems/ruby-1.9.3-p125/bundler/gems/spree_flexi_variants-7443a8462000/app/models/spree/order_decorator.rb:4:in `add_variant'
app/models/spree/order.rb:471:in `block in merge!'
...
```

**Comment by gmacdougall** [comment]
Sorry for the spam.  I have resolved this issue in our fork and submitted a pull request.

**Comment by jsqu99** [comment]
no need to apologize.  thank you very much for reporting.

i'm absolutely slammed crazy busy ATM but will take a look and pull ASAP.

thanks!
