### ISSUE TITLE
Spree NoMethodError 

### ISSUE THREAD

**Issue by lethjakman** [jsqu99/spree_flexi_variants#52]
This is the error I got. 

http://pastebin.com/4ZyBLP3q

The method .presentation isn't found. I'm using spree 1.1.3 with the master branch. Also, 

gem 'spree_flexi_variants', :git=>'git@github.com:jsqu99/spree_flexi_variants.git'

Does not work, I had to modify it to 

gem 'spree_flexi_variants', :git=>'https://github.com/jsqu99/spree_flexi_variants.git'

**Comment by jsqu99** [comment]
thanks for reporting.

i'm actually in ireland on vacation at the moment, but i'll look at this
asap.

it looks like it's expecting an option value in your variant that isn't
there.

you might want to put a debugger above that line and look at option.option_type
and @variant.option_values to see what it's trying to match.

thanks

**Comment by lethjakman** [comment]
Wow, a response on your vacation. That's some good service! Don't feel the need to respond, I just wanted to report my findings. 

This is actually only true in the Pow server for mac. I switched over to the rails server with the debugger gem enabled to try and figure this out, and it runs perfectly!

**Comment by juancabrito** [comment]
I don't know if this is related but I'm getting this error:

```
undefined method `admin_customizable_product_option_path' for #<#<Class:0xae89ea0>:0xae97c94>
Extracted source (around line #5):

2:   <td><%= f.text_field :name, :readonly => true, :disabled => true %></td>
3:   <td><%= f.text_field :presentation %></td>
4:   <td><%= f.text_area :description, {:style=>'height: auto;', :rows => 3, :cols => 25} %></td>
5:   <td class="actions"><%= link_to_remove_fields t("remove"), f %></td>
6: </tr>
```

I'm using version 1-3-stable

**Comment by jsqu99** [comment]
are you trying this w/ the latest spree?  if so, it won't work, as the
admin app has drastically changed.

**Comment by juancabrito** [comment]
Yes I'm trying with 1-3 but I'm also trying with 1-2 using the branch
1-2-stable of flexi variants but I'm getting the same error.

2012/12/12 Jeff Squires notifications@github.com

> are you trying this w/ the latest spree? if so, it won't work, as the
> admin app has drastically changed.
>

**Comment by jsqu99** [comment]
I just got an error w/ another route.  i think it is related and has something to do w/ the differences between a couple different spree 1.2 versions

**Comment by jsqu99** [comment]
I believe the culprit to be: https://github.com/spree/spree/commit/cbcb7937b2187dfe6b3fd7e752f8681e08cc786b#L2R151

I'm going to check in an override of that method in a few minutes

**Comment by jalberto** [comment]
Thanks @nostopbutton it works for me in spree-1.3
