### ISSUE TITLE
Could you add a calendar to the variants?

### ISSUE THREAD

**Issue by jz2036** [jsqu99/spree_flexi_variants#53]
This looks like a very powerful extension. I would like to use it for a rental website.

Basically, I need a calendar as variants for customs to specify the expect renting dates (from/to) and calculate based on that. Any hint on how to implement this function using your extension? Or, could you add this feature later? I am looking forward to it!

Thank you so much!

**Comment by jsqu99** [comment]
Thanks!

You could totally do this easily.

You would have a customization calculator that had two elements - from & to.

You'd write your custom UI to provide those two fields to rails.

take a look at a 2d calculator here: http://pastie.org/4709396

That powers this page: http://scframes.com/products/barre-street

(excuse the atrocious UI.  long story there).
