### ISSUE TITLE
How we know that a certain combination is out of stock?

### ISSUE THREAD

**Issue by davidslvto** [jsqu99/spree_flexi_variants#54]
Hi,

I'm using your gem, and this question came, I don't see anything that allows me to say that a certain combination has for example 20 products in stock.

**Comment by jsqu99** [comment]
Hello,

Unfortunately there's not inventory management in this version.

I had begun a new version w/ that in mind but development on it has
stalled.  You can see the screenshots if you take a look at the v2 branch.
