### ISSUE TITLE
Ability to edit/update customized product from cart form?

### ISSUE THREAD

**Issue by gregmurray** [jsqu99/spree_flexi_variants#58]
I was wondering if there is any current functionality (or if anyone has suggestions) to have an edit product button on the cart form that links back to the product page and propogates all ad-hoc fields with the selected values.  I want to allow my users to have the ability to edit and update the customized product without having to start over.

**Comment by jsqu99** [comment]
that's tricky b/c the ad hoc stuff is stored at the line item level, not the product.

but you could always find the corresponding line item from the current_order and set the selects appropriately.

shouldn't be too hard

**Comment by gregmurray** [comment]
Thanks.  I am now storing the customizations in a new model (productbuilds) because I want my users to have the ability to save and update products they have customized.  I have it all set up and working and am now trying to add the productbuild id to the line item so that it can be referenced back to the productbuild and updated/edited.  I am trying to wrap my head around how the line items are created and how I can do this but I am not quite understanding how spree is creating these line items.  I have looked at your files and line_item_decorators yet I still cant quite figure it out.  Do you have any suggestions that can put me on the right path to get this done?

**Comment by jsqu99** [comment]
in spree 1.3 (which is not yet supported here): https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb#L252

also these files might help as well: https://github.com/jsqu99/spree_flexi_variants/blob/master/lib/ad_hoc_utils.rb
https://github.com/jsqu99/spree_flexi_variants/blob/master/lib/product_customizations.rb

**Comment by gregmurray** [comment]
Thanks.   I got it working properly.
