### ISSUE TITLE
uninitialized constant SpreeFlexiVariantsHooks::Deface

### ISSUE THREAD

**Issue by binaryphile** [jsqu99/spree_flexi_variants#6]
Got this error with a fresh latest spree install, ruby 1.8.7, rails 3.0.7, gem 1.5.2, bundler 1.0.14, installed on windows with railsinstaller.  (bundler 1.0.14 needs a recent patch on windows, btw)

I added the following to the end of my Gemfile and ran "bundle install", which seemed to work until I did "rails s":

gem 'spree_flexi_variants', :git => 'git://github.com/jsqu99/spree_flexi_variants.git'

Running the server, which worked before the install, results in the error in the subject.

**Comment by jsqu99** [comment]
hmmm...i will investigate asap.  can you email me your full Gemfile?  jeff.squires@gmail.com

**Comment by jsqu99** [comment]
Your Gemfile entries:

gem 'spree'
gem 'spree_flexi_variants', :git => 'git://github.com/jsqu99/spree_flexi_variants.git'

Are saying:
 "use the latest spree gem" (currently 0.60.x)
 "use the master flexi branch" (not compatible w/ 0.60.x").

I have in the README Installation section:

gem 'spree', :git => 'git://github.com/spree/spree.git'  # latest master branch
gem 'spree_flexi_variants', :git=>'git@github.com:jsqu99/spree_flexi_variants.git'  # latest master branch

Which should get you the right combination

**Comment by binaryphile** [comment]
I see...you're saying to use the latest spree code.  I will give this a shot.  I'm assuming it's pretty stable if you're recommending it.  Thanks.  Sorry I missed that in the README.

**Comment by jsqu99** [comment]
well there are two options:

if you want to use the latest stable spree version, use the
pre-deface-stable branch, along w/ the spree gem.

if you want bleeding edge, use master.

both scenarious are listed in the readme
