### ISSUE TITLE
Problem in new Spree 1-3-2-stable Admin: option_types#edit

### ISSUE THREAD

**Issue by jetsgit** [jsqu99/spree_flexi_variants#60]
Clicking on products-option types -edit gives the following error:

ArgumentError in Spree/admin/option_types#edit 

```
 /home/jet/.rvm/gems/ruby-1.9.3-p194@spree-1-3-stable/bundler/gems/spree_flexi_variants-160fa999fd77/app/helpers/spree/admin/base_helper_decorator.rb:4:in `link_to_remove_fields'
```

...and here is the relevant base_helper_decorator.rb code, looks like it has been visited before:

```
     BaseHelper.module_eval do
  def link_to_remove_fields(name, f)
    # fixes https://github.com/jsqu99/spree_flexi_variants/issues/52 by reverting back to 'old spree' version
    f.hidden_field(:_destroy) + link_to_with_icon(:delete, name, '#', :class => 'remove_fields')
  end
end
```

Any ideas on how to fix this Jeff?

Everything else has been working great in Spree v.1.3.2-beta

Thanks!

   Eric

**Comment by jetsgit** [comment]
Removing _base_helper_decorator.rb appears to have solved the problem.
Nothing like going back to the well!

**Comment by sfcgeorge** [comment]
If the fix is deleting that file, could the change be merged in? Thanks
