### ISSUE TITLE
spree-1-3-stable branch

### ISSUE THREAD

**Issue by jetsgit** [jsqu99/spree_flexi_variants#65]
Jeff, did you have a chance to look at the diff I made in Issue #61 (Spreee 1 3 Stable) between the working version from my spree-1-3-stable branch and the working version on Ted Lilley's master branch?  Thought your insight and a decision on which would be best to 
proceed with as basis for a spree-1-3-stable, or a combination of the 2---if you would indeed like to support that.

What do you think?

Thanks!  Jet

**Comment by jetsgit** [comment]
Spree 1-3-stable New Order in Admin is broken with flexi-variants. It looks like some major changes to get that working. Is that something you are considering?

**Comment by jetsgit** [comment]
Text displayed instead of icons and tooltips in ad_hoc_option_types edit.

**Comment by jsqu99** [comment]
Again, very sorry for disappearing on you @bluehandtalking .  I've had some personal things distracting me in 2013.  I'm going to close this for now, hoping that https://github.com/jsqu99/spree_flexi_variants/tree/spree-1-3-stable addressed these.  Feel free to reopen if necessary.
