### ISSUE TITLE
uninitialized constant JSON

### ISSUE THREAD

**Issue by nimish79** [jsqu99/spree_flexi_variants#7]
I get the following message:

NameError in Products#show

Showing /home/nimish/.bundler/ruby/1.8/spree_flexi_variants-d633203dfb90/app/views/products/_customizations.html.erb where line #36 raised:

<code>uninitialized constant JSON</code>

Extracted source (around line #36):
<code>33:                 <% if lookup.exists?(partial_name,nil,true) %>
34:                     <%= render :partial => partial_name, :locals=>{:customizable_product_option => option, :param_prefix => param_prefix} %>
35:                 <% else %>
36:                     <%= text_field_tag "#{param_prefix}[#{option.id}]","", custom_html_options(option) %>
37:                   <% end %>
</code>

**Comment by jsqu99** [comment]
Are you comfortable modifying the source of the extension?

If so, would you please try modifying that file to have it start like:

ProductsHelper.module_eval do

  require 'json'

And see if that fixes the problem?

I'm wondering if you need to also add gem 'json' to the Gemfile

**Comment by jsqu99** [comment]
I actually just pushed that fix so you can pull it if you like.  I'm not sure about the Gemfile entry.  We might still need that.  Please let me know how it goes.  Thanks for reporting.

**Comment by nimish79** [comment]
Made the changes. Worked after I added gem 'json' to the Gemfile. Thx.

BTW, how about having an Image Upload functionality as a part of the
customization. This would be useful for stuff like T-shirts or Mugs where
someone cd upload the picture to be printed as well.
