### ISSUE TITLE
UI  Renovation for Admin Orders / New Order

### ISSUE THREAD

**Issue by jetsgit** [jsqu99/spree_flexi_variants#72]
There needs to be an overhaul to get spree_flexi_variant to work with 'New Order' in the Admin. 

Since it is very possible to have  a combination of variants available for a product, select fields for each variant should be generated when a product is selected in 

' Select a Variant' . 

The above should be:

' Select a Product'

When product is selected, the appropriate selection types for ad_hoc_option_types
would be generated.

If you think about it, the existing method built into Spree 1-3-stable is
not so great. To actually select a specific variant for a product you might have something
like:

Colors: 10 Choices
Design Pattern: 20 Choices
Size: 4 Choices

Using the variant specific scheme now in Spree, that would generate a list of
800 choices, or the Mother Of All Selection Lists.

There should be a select field for each variant to make this a good UX.

   Jet

**Comment by jetsgit** [comment]
Has this been fixed elsewhere?

**Comment by jsqu99** [comment]
@bluehandtalking for some reason I never saw this :-(

Fyi, I'm working on getting some/all of your commits integrated.
