### ISSUE TITLE
AJAX Pricing Updates

### ISSUE THREAD

**Issue by nimish79** [jsqu99/spree_flexi_variants#8]
The Wiki mentions that the pricing updates should happen automatically but that didn't happen. So I went and checked lib/ spree_flexi_variants.rb in the bundled gem and found that the file is empty. product_customizations.rb and spree_flexi_variants_hooks.rb had the appropriate code but not spree_flexi_variants.rb. Is that the problem or am I going down the wrong lane?

**Comment by jsqu99** [comment]
I'm glad the json fix worked.

fyi, just yesterday I started on an image customization!  I pushed a branch
last night that is a work in progress (don't use it yet).

Maybe there was a problem during your download?
https://github.com/jsqu99/spree_flexi_variants/blob/pre-deface-stable/lib/spree_flexi_variants.rb
shows
the file is there.

The pricing updates should happen automatically.  Why don't you try removing
and reinstalling?

Let me know how it works.

Thanks,

Jeff

**Comment by nimish79** [comment]
Shall remove and install again.

Really looking forward to the image customisation piece.

Sent from my iPad

On 28-Jun-2011, at 17:50, jsqu99
reply@reply.github.com
wrote:

> I'm glad the json fix worked.
> 
> fyi, just yesterday I started on an image customization!  I pushed a branch
> last night that is a work in progress (don't use it yet).
> 
> Maybe there was a problem during your download?
> https://github.com/jsqu99/spree_flexi_variants/blob/pre-deface-stable/lib/spree_flexi_variants.rb
> shows
> the file is there.
> 
> The pricing updates should happen automatically.  Why don't you try removing
> and reinstalling?
> 
> Let me know how it works.
> 
> Thanks,
> 
> Jeff
> 
> On Tue, Jun 28, 2011 at 12:26 AM, nimish79 <

**Comment by jsqu99** [comment]
Excellent.

Well keep your eyes on the new branch.

I'm working on it full time right now.

**Comment by nimish79** [comment]
While reinstalling, the spree_flexi_variants.rb file did appear, the prices aren't getting updated automatically. Do I need to edit spree_flexi_variants.rb to make it work? Or is there a change I need to make in the Spree core files?

**Comment by jsqu99** [comment]
I belive it should work out of the box.  I wrote something either on the readme or the wiki re: setting the conguration option

**Comment by jsqu99** [comment]
I've recently had some issues w/ the preferences.

try adding:

```
  Spree::Config.set :use_ajax_pricing_updates => true
```

in the following location within ./lib/spree_flexi_variants.rb:

require 'spree_core'
require 'spree_flexi_variants_hooks'

module SpreeFlexiVariants
  class Engine < Rails::Engine

```
config.autoload_paths += %W(#{config.root}/lib)

def self.activate
  Dir.glob(File.join(File.dirname(__FILE__),
```

"../app/*_/__decorator*.rb")) do |c|
        Rails.env.production? ? require(c) : load(c)
      end

```
  Spree::Config.set :use_ajax_pricing_updates => true
```

**Comment by jsqu99** [comment]
OK, I have just massively overhauled the preferences on the master branch.

I finally have it done correctly and you shouldn't see any problems.  Please let me know if that's not correct.

Also, I'd use the master branch only.  There is more functionality, and all my tests are passing.  Lots of updates coming very soon.

**Comment by nimish79** [comment]
So should I just remove the extension and then add this to the gemfile...

gem 'spree_flexi_variants', :git => 'git://github.com/jsqu99/spree_flexi_variants.git'

No need for :branch => 'pre-deface-stable'?

**Comment by jsqu99** [comment]
Yes. Please give that a try at your convenience and let me know how it goes. You will need to run the rake flexi....install task again to cp the new migrations. Also add to your gemfile carrierwave and rmagick 

Then bundle && rake db:migrate

**Comment by nimish79** [comment]
Yep it worked. The carrierwave gem got installed without having to add to my
Gemfile.
