### ISSUE TITLE
Prototypes

### ISSUE THREAD

**Issue by dbwinger** [jsqu99/spree_flexi_variants#83]
Thanks so much for this extension, @jsqu99 . As far as I can tell, using the ad hoc variants makes prototypes irrelevant.  Is that correct, or am I missing something?  I'd love to still be able to help my clients save time by still being able to use prototypes to set up the ad hoc options.  I may work on that and submit a pull request, but just wanted to first check and make sure I wasn't missing a way that I can already do that, as I only just started using your extension.  Thanks again!

**Comment by jsqu99** [comment]
Thanks.

Correct on the prototypes question (as far as options/variants are concerned).

Feel free to submit any pull requests (especially if you want to work on spree-2-stable :-) )

**Comment by dbwinger** [comment]
Thanks. I will.  I'm currently using jdurand's 2.0 version https://github.com/jdurand/spree_flexi_variants which seems to be working well, but like I said, I haven't used it too thoroughly yet.
