### ISSUE TITLE
Add Engraving validation

### ISSUE THREAD

**Issue by BRZInc** [jsqu99/spree_flexi_variants#84]
Hello,

Thanks a lot for incredible gem - I've started developing something similar, however it looks like you've done all the work already.

After installation of spree_flexi_variants I've figured out that there is a need to validate length of Engravings (Customization type). It would be excellent if you could add validation by regex.

Is there any possibility to add this feature?

**Comment by jsqu99** [comment]
Thanks. I'm working on giving the extension some long-overdue updating to spree 2.1

That length validation might be unique to your use case? 

If I'm mistaken, you could always add another preference and submit a PR
