### ISSUE TITLE
ad hoc option weights

### ISSUE THREAD

**Issue by dbwinger** [jsqu99/spree_flexi_variants#86]
I think I know the answer to this (no), but is there a way to specify weight differences for the ad hoc options?  I was planning to use weight as one of the option types but I also need to use weight for shipping calculation.  I'm sure I can do some customization to make this happen, but wanted to make sure I'm not missing something built-in that will help me accomplish this.

**Comment by jsqu99** [comment]
Your guess was correct :-)
