### ISSUE TITLE
NameError in Admin/orders#edit 

### ISSUE THREAD

**Issue by ArjanL** [jsqu99/spree_flexi_variants#9]
I use spree_flexi_variants with multiple select options, it worked fine but since a upgrade i get the following error in admin/orders/edit:

Showing /Users/--/.bundler/ruby/1.8/spree_flexi_variants-000b5d6dc274/app/views/shared/_additional_line_item_fields.html.erb where line #11 raised: 

undefined local variable or method `item' for #<#Class:0x8601514:0x85fe51c>

```
 8: 
 9: <dl>
10:   <%# TODO: group multi-select options (e.g. toppings) %>
11:   <% item.ad_hoc_option_values.each do |pov| %>
12:     <dt><%= pov.option_value.option_type.presentation %> (<%= format_price pov.price_modifier %>)</dt>
13:     <dd><%= pov.option_value.presentation %></dd>
14:   <% end %>
```

Does someone got a solution for this?

**Comment by jsqu99** [comment]
I am going to look at this today.

Thanks for reporting.

**Comment by jsqu99** [comment]
I'm wondering if you are using the pre-deface-stable branch.

I'm on master, and I went to two urls, like:

http://localhost:3000/admin/orders/R440885855
and
http://localhost:3000/admin/orders/R440885855/edit

and they both render correctly. 

I'll investigate that branch.

**Comment by ArjanL** [comment]
I  am working on master now and most of the things work correctly.
There is only still one problem, i'm not shure if this problem comes from spree_flexi_variants, but my product prices show up as "$ NaN". During the checkout processs i see the prices just like they belong to, but when i go to the last step in checkout i get the following error:

TypeError in CheckoutController#update
instance of IO needed

And when i look at the parameter for the db in amount i see this: 

{"authenticity_token"=>"RHIezjjchDZpLvTF2TLzrtLPXfgWa1YG2xsMNOuaEpI=",
 "_method"=>"put",
 "utf8"=>"✓",
 "order"=>{"payments_attributes"=>[{"payment_method_id"=>"2",
 "amount"=>#<BigDecimal:891d310,
'0.97E1',
8(8)>}],
 "store_credit_amount"=>"0.0"},
 "state"=>"payment"}

**Comment by jsqu99** [comment]
The error you were getting before, was that on pre-deface-stable?   

I see you are using the store credits extension?

What page shows the NaN?

**Comment by ArjanL** [comment]
The error that i had before was on a fork from MrRuRu.
The products detail pages shows the NaN.

**Comment by ArjanL** [comment]
Never mind...problem solved! I forgot that i had a partial _pricing.html.erb in my layout. Excuse me.

**Comment by jsqu99** [comment]
I'm glad you are in good shape now.

Feel free to give feedback or report any other issues you might find.

Good Luck,

Jeff
